function [f,fe,fx,s,d,p] = keepStates_simple(f,fe,fx,s,d,p,info,tix)
% stores the variables of the previous time step in .prev fields
%
% Inputs:
%    - info
%   - the variables to keep are generated by code analyzer using a check on
%   s.prev. and d.prev. 
%   - if the prev fields appear in the RHS of a equation, the variable will
%   be automatically added to variables to keep
%   - Never assign any values directly to .prev fields
%
% Outputs:
%   - s.prev.[var] 
%   - d.prev.[var]
%
% Modifies:
%     - None
%
% References:
%    - 
%
% Created by:
%   - Martin Jung (mjung)
%   - Sujan Koirala (skoirala)
%
% Versions:
%   - 1.0 on 11.01.2018 (mjung): automatic handling using setupCode
%   - 1.1 on 11.11.2019 (skoirala): documentation and cleanup
%%
%--> get the variables to keep (previous time step)
cvars_source        =   info.tem.model.code.variables.to.keepSource;
cvars_destination    =   info.tem.model.code.variables.to.keepDestination;
%--> store the variables
for ii  =   1:length(cvars_source)
    sstr            =   [char(cvars_destination(ii)) ' = ' char(cvars_source(ii))];
    eval(sstr);
end
end

