% a script to run an experiment to optimize one fluxnet site
try
    gone
catch
end

%% setup paths
for fn = {'tools','model','optimization'}
    addpath(genpath(['../../' fn{1}]),'-begin')
end
outpath='/Net/Groups/BGI/work_3/sindbad/data/testBeds/output';
inpath='/Net/Groups/BGI/work_3/sindbad/data/testBeds/input/US-Ha1.2000-2015.nc';
testName='cCycleOpti';
%% provide an experiment configuration file
expConfigFile               =   'testBeds/cCycleOpti/settings_cCycleOpti/experiment_runOpti.json';

 % setup explicit spinup
%strN        = '% setup explicit spinup';
%strN2       = 'explicit';
zSequence   = struct(...
'funHandleSpin',{'runCoreTEM','runCoreTEM','spin_cCycle_CASA','runCoreTEM'},...
'funHandleStop',{[],[],[],[]},...
'funAddInputs',{{1,0,0},{0,1,0},{21},{0,1,0}},...
'nLoops',{1,20,1,1}...
); 

%% run the experiment
[f_def,fe_def,fx_def,s_def,d_def,p_def,precOnceData_def,info_def...
    ,fSU_def,feSU_def,fxSU_def,sSU_def,dSU_def,precOnceDataSU_def,infoSU_def,obs_def,cost_def] = workflowExperiment(expConfigFile,...
    'info.tem.spinup.sequence',zSequence,...
    'info.tem.spinup.flags.recycleMSC', true,...
    'info.tem.spinup.flags.saveSpinup', false,...
    'info.tem.forcing.oneDataPath',inpath,...
    'info.experiment.outputDirPath',outpath,...
    'info.experiment.name',testName,...
    'info.opti.constraints.oneDataPath',inpath...
    );

[f_opt,fe_opt,fx_opt,s_opt,d_opt,p_opt,precOnceData_opt,info_opt,...
    fSU_opt,feSU_opt,fxSU_opt,sSU_opt,dSU_opt,precOnceDataSU_opt,infoSU_opt,obs_opt,cost_opt] = workflowExperiment(expConfigFile,...
    'info.tem.spinup.sequence',zSequence,...
    'info.tem.spinup.flags.recycleMSC', true,...
    'info.tem.spinup.flags.saveSpinup', false,...
    'info.tem.forcing.oneDataPath',inpath,...
    'info.experiment.outputDirPath',outpath,...
    'info.experiment.name',testName,...
    'info.opti.constraints.oneDataPath',inpath...
    );
