function [f,fe,fx,s,d,p] = prec_cFlowfpVeg_CASA(f,fe,fx,s,d,p,info)
% effect of vegetation on transfer rates between pools (Potter et al 1993)

% s.cd.p_cFlowfpVeg_fVeg = zeros(nPix,numel(info.tem.model.c.nZix)); %sujan
%s.cd.p_cFlowfpVeg_fVeg      =   info.tem.helpers.arrays.zerospixzix.c.cEco;
s.cd.p_cFlowfpVeg_F      =   repmat(info.tem.helpers.arrays.zerospixzix.c.cEco,1,1,...
                                        info.tem.model.variables.states.c.nZix.cEco);
                                    s.cd.p_cFlowfpVeg_E = s.cd.p_cFlowfpVeg_F;
% ADJUST cFlow BASED ON PARTICULAR PARAMETERS...
%   SOURCE,TARGET,INCREMENT... 
aM    = {...
    'cVegLeaf',     'cLitLeafM',    s.cd.p_cTaufpVeg_MTF;...
    'cVegLeaf',     'cLitLeafS',    1 - s.cd.p_cTaufpVeg_MTF;...
    'cVegWood',     'cLitWood',     1;...
    'cVegRootF',    'cLitRootFM',   s.cd.p_cTaufpVeg_MTF;...
    'cVegRootF',    'cLitRootFS',   1 - s.cd.p_cTaufpVeg_MTF;...
    'cVegRootC',    'cLitRootC',    1;...
    'cLitLeafS',    'cSoilSlow',    s.cd.p_cTaufpVeg_SCLIGNIN;...
    'cLitLeafS',    'cMicSurf',     1 - s.cd.p_cTaufpVeg_SCLIGNIN;...
    'cLitRootFS',   'cSoilSlow',    s.cd.p_cTaufpVeg_SCLIGNIN;...
    'cLitRootFS',   'cMicSoil',     1 - s.cd.p_cTaufpVeg_SCLIGNIN;...
    'cLitWood',     'cSoilSlow',    p.cFlowfpVeg.WOODLIGFRAC;...
    'cLitWood',     'cMicSurf',     1 - p.cFlowfpVeg.WOODLIGFRAC;...
    'cLitRootC',    'cSoilSlow',    p.cFlowfpVeg.WOODLIGFRAC;...
    'cLitRootC',    'cMicSoil',     1 - p.cFlowfpVeg.WOODLIGFRAC;...
    'cSoilOld',     'cMicSoil',     1;...
    'cLitLeafM',    'cMicSurf',     1;...
    'cLitRootFM',   'cMicSoil',     1;...
    'cMicSurf',     'cSoilSlow',    1;...
    };


for ii = 1:size(aM,1)
    ndxSrc                  =   info.tem.model.variables.states.c.zix.(aM{ii,1});
    ndxTrg                  =   info.tem.model.variables.states.c.zix.(aM{ii,2}); %sujan is this 2 or 1?
    for iSrc = 1:numel(ndxSrc)
        for iTrg = 1:numel(ndxTrg)
%             s.cd.p_cFlowfpVeg_fVeg(ndxTrg(iTrg),ndxSrc(iSrc)) = aM{ii,3};
            
             s.cd.p_cFlowfpVeg_F(:,ndxTrg(iTrg),ndxSrc(iSrc)) = aM{ii,3};%sujan
        end
    end
end

end %function
