function [f,fe,fx,s,d,p] = coreTEM(f,fe,fx,s,d,p,info)
% The core driver of SINDBAD TEM that loops through all the modules and
% runs time loop
%
% Requires:
%   - f: forcing
%   - fe: extra forcing precomputed outside time loop (exclusively out of runPreCompOnce)
%   - fx: structure with all fluxes
%   - s: structure with all state variables
%   - d: structure with all diagnostics
%   - p: structure with all parameters
%   - info: all additional information needed to run modules
%
% Purposes:
%   - runs all modules and fills the SINDBAD structures with simulation results
%
% Conventions:
%   - The modules are executed in the order called in the coreTEM 
%   - If order of call are to be changed, a copy of coreTEM should be created and corresponding path should be provided in modelStructure.json
%   - Default approach for each module is dummy (empty approach with no calculation)
%   - Other approaches should be set in modelStructure.json
%   - Through runCoreTEM.m
%       - If runGenCode is true, the generated version of precOnce and core with selected approaches per model are used
%       - If runGenCode is false, 
%           - original handles for coreTEM.m and
%   runPrecOnceTEM.m are used for forward run
%           - corresponding reduced versions, coreTEM4spinup.m and
%       runPrecOnceTEM4Spinup.m, 
%       are used for spinup
%           - NOTE THAT THESE FUNCTIONS AUTOMATICALLY TRACK CHANGES IN
%       coreTEM.m AND DO NOT NEED MODIFICATIONS WHEN coreTEM.M IS COPIED
%       AND CHANGED
%
% Created by:
%   - Nuno Carvalhais (ncarval@bgc-jena.mpg.de)
%   - Martin Jung (mjung@bgc-jena.mpg.de)
%   - Sujan Koirala (skoirala@bgc-jena.mpg.de)
%
% References:
%
% Versions:
%   - 1.1 on 20.11.2019 : skoirala : multiple changes in name of modules
%   - 1.1 on 10.07.2018 : skoirala : cleanup and documentation
%   - 1.0 on 01.05.2018
%
%%
% -------------------------------------------------------------------------
% Do precomputations
% -------------------------------------------------------------------------
for prc = 1:numel(info.tem.model.code.prec)
    if info.tem.model.code.prec(prc).runAlways == 1
        [f,fe,fx,s,d,p]	= info.tem.model.code.prec(prc).funHandle(f,fe,fx,s,d,p,info);
    end
end
% -------------------------------------------------------------------------
% CARBON AND WATER FLUXES ON LAND
% -------------------------------------------------------------------------
% get the model structure generated by setupCode.m
ms	= info.tem.model.code.ms;

% LOOP : loop through the whole length of of the forcing dataset
for tix = 1:info.tem.helpers.sizes.nTix
    % ---------------------------------------------------------------------
    % Get rainfall, snowfall, and rainfall intensities
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.rainSnow.funHandle(f,fe,fx,s,d,p,info,tix);          % set rain and snow to fe.rainSnow.
    [f,fe,fx,s,d,p]     =   ms.rainInt.funHandle(f,fe,fx,s,d,p,info,tix);           % set rainfall intensity
    % ---------------------------------------------------------------------
    % Get variables for previous time step and keep in s.prev. or d.prev
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.keepStates.funHandle(f,fe,fx,s,d,p,info,tix);        % keep states from previous time step to s.prev    
    [f,fe,fx,s,d,p]     =   ms.getStates.funHandle(f,fe,fx,s,d,p,info,tix);         % get the amount of water at the beginning of timestep
    % ---------------------------------------------------------------------
    % 0 - Terrain - to get the terrain params   
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.pTopo.funHandle(f,fe,fx,s,d,p,info,tix);             % topographic properties
    % ---------------------------------------------------------------------
    % 0 - SOIL - to get the soil related params
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.soilTexture.funHandle(f,fe,fx,s,d,p,info,tix);       % soil texture (sand,silt,clay, and organic matter fraction)
    [f,fe,fx,s,d,p]     =   ms.pSoil.funHandle(f,fe,fx,s,d,p,info,tix);             % soil properties (hydraulic properties)
    [f,fe,fx,s,d,p]     =   ms.wSoilBase.funHandle(f,fe,fx,s,d,p,info,tix);         % distribution of soil hydraulic properties over depth
    % ---------------------------------------------------------------------
    % 0 - Root      - root depth and distribution
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.rootMaxD.funHandle(f,fe,fx,s,d,p,info,tix);          % maximum rooting depth
    [f,fe,fx,s,d,p]     =   ms.rootFrac.funHandle(f,fe,fx,s,d,p,info,tix);          % distribution of maximum water uptake by root per soil layer
    % ---------------------------------------------------------------------
    % 0 - VEG - LC changes / phenology / disturbances / structure
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.pVeg.funHandle(f,fe,fx,s,d,p,info,tix);              % vegetation/structural properties
    [f,fe,fx,s,d,p]     =   ms.fAPAR.funHandle(f,fe,fx,s,d,p,info,tix);             % fraction of Absorbed Photosynthetically Active Radiation
    [f,fe,fx,s,d,p]     =   ms.EVI.funHandle(f,fe,fx,s,d,p,info,tix);               % EVI
    [f,fe,fx,s,d,p]     =   ms.cLAI.funHandle(f,fe,fx,s,d,p,info,tix);              % leaf area index
    [f,fe,fx,s,d,p]     =   ms.vegFrac.funHandle(f,fe,fx,s,d,p,info,tix);           % fractional coverage of vegetation
    % ---------------------------------------------------------------------
    % 1 - Snow
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.wSnowFrac.funHandle(f,fe,fx,s,d,p,info,tix);         % add snow fall and calculate snow cover fraction
    [f,fe,fx,s,d,p]     =   ms.evapSub.funHandle(f,fe,fx,s,d,p,info,tix);           % calculate sublimation and update snow water equivalent
    [f,fe,fx,s,d,p]     =   ms.snowMelt.funHandle(f,fe,fx,s,d,p,info,tix);          % calculate snowmelt and update s.w.wSnow
    % ---------------------------------------------------------------------
    % 2 - Water 
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.evapInt.funHandle(f,fe,fx,s,d,p,info,tix);           % interception evaporation
    [f,fe,fx,s,d,p]     =   ms.roInf.funHandle(f,fe,fx,s,d,p,info,tix);             % infiltration excess runoff
    [f,fe,fx,s,d,p]     =   ms.roSat.funHandle(f,fe,fx,s,d,p,info,tix);             % saturation runoff
    [f,fe,fx,s,d,p]     =   ms.wSoilSatFrac.funHandle(f,fe,fx,s,d,p,info,tix);      % saturation runoff
    [f,fe,fx,s,d,p]     =   ms.evapSoil.funHandle(f,fe,fx,s,d,p,info,tix);          % soil evaporation
    [f,fe,fx,s,d,p]     =   ms.wSoilRec.funHandle(f,fe,fx,s,d,p,info,tix);          % recharge the soil
    [f,fe,fx,s,d,p]     =   ms.roInt.funHandle(f,fe,fx,s,d,p,info,tix);             % interflow
    [f,fe,fx,s,d,p]     =   ms.roOverland.funHandle(f,fe,fx,s,d,p,info,tix);        % land over flow (sum of saturation and infiltration excess runoff)
                                                                                    % if e.g. infiltration excess runoff and or saturation runoff are not
                                                                                    % explicitly modelled then assign a dummy handle that returnes zeros and
                                                                                    % lump the FastRunoff into interflow
    [f,fe,fx,s,d,p]     =   ms.roSurf.funHandle(f,fe,fx,s,d,p,info,tix);            % runoff from surface water storages
    [f,fe,fx,s,d,p]     =   ms.wGWRec.funHandle(f,fe,fx,s,d,p,info,tix);            % recharge the groundwater
    [f,fe,fx,s,d,p]     =   ms.roBase.funHandle(f,fe,fx,s,d,p,info,tix);            % baseflow
    [f,fe,fx,s,d,p]     =   ms.wGW2wSoil.funHandle(f,fe,fx,s,d,p,info,tix);         % Groundwater soil moisture interactions (e.g. capilary flux, water
                                                                                    % table in root zone etc)
    % ---------------------------------------------------------------------
    % 3 - Transpiration and GPP
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.WUE.funHandle(f,fe,fx,s,d,p,info,tix);               % estimate WUE
    [f,fe,fx,s,d,p]     =   ms.tranfwSoil.funHandle(f,fe,fx,s,d,p,info,tix);        % supply limited Transpiration
    [f,fe,fx,s,d,p]     =   ms.GPPpot.funHandle(f,fe,fx,s,d,p,info,tix);            % maximum instantaneous radiation use efficiency
    [f,fe,fx,s,d,p]     =   ms.GPPfRdiff.funHandle(f,fe,fx,s,d,p,info,tix);         % effect of diffuse radiation
    [f,fe,fx,s,d,p]     =   ms.GPPfRdir.funHandle(f,fe,fx,s,d,p,info,tix);          % effect of direct radiation
    [f,fe,fx,s,d,p]     =   ms.GPPfTair.funHandle(f,fe,fx,s,d,p,info,tix);          % effect of temperature
    [f,fe,fx,s,d,p]     =   ms.GPPfVPD.funHandle(f,fe,fx,s,d,p,info,tix);           % VPD effect
    [f,fe,fx,s,d,p]     =   ms.GPPdem.funHandle(f,fe,fx,s,d,p,info,tix);            % combine effects as multiplicative or minimum
    [f,fe,fx,s,d,p]     =   ms.GPPfwSoil.funHandle(f,fe,fx,s,d,p,info,tix);         % if 'coupled' requires access to iwue param    
    [f,fe,fx,s,d,p]     =   ms.GPPact.funHandle(f,fe,fx,s,d,p,info,tix);            % combine effects as multiplicative or minimum    
    [f,fe,fx,s,d,p]     =   ms.tranAct.funHandle(f,fe,fx,s,d,p,info,tix);           % if coupled computed from GPP
    [f,fe,fx,s,d,p]     =   ms.wRootUptake.funHandle(f,fe,fx,s,d,p,info,tix);       % root water uptake (extract water from soil)
    % ---------------------------------------------------------------------
    % 4 - Climate and other effects on metabolic processes
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.cCycleBase.funHandle(f,fe,fx,s,d,p,info,tix);        % pool structure of the carbon cycle
    [f,fe,fx,s,d,p]     =   ms.cTaufTsoil.funHandle(f,fe,fx,s,d,p,info,tix);        % effect of soil temperature on decomposition rates
    [f,fe,fx,s,d,p]     =   ms.cTaufwSoil.funHandle(f,fe,fx,s,d,p,info,tix);        % effect of soil moisture on decomposition rates
    [f,fe,fx,s,d,p]     =   ms.cTaufLAI.funHandle(f,fe,fx,s,d,p,info,tix);          % calculate litterfall scalars (that affect the changes in the vegetation k)
    [f,fe,fx,s,d,p]     =   ms.cTaufpSoil.funHandle(f,fe,fx,s,d,p,info,tix);        % effect of soil texture on soil decomposition rates
    [f,fe,fx,s,d,p]     =   ms.cTaufpVeg.funHandle(f,fe,fx,s,d,p,info,tix);         % effect of vegetation properties on soil decomposition rates
    [f,fe,fx,s,d,p]     =   ms.cTauAct.funHandle(f,fe,fx,s,d,p,info,tix);           % combine effects of different factors on decomposition rates
    [f,fe,fx,s,d,p]     =   ms.RAfTair.funHandle(f,fe,fx,s,d,p,info,tix);           % temperature effect on autotrophic maintenance respiration
    % ---------------------------------------------------------------------
    % 5 - Allocation of C within plant organs
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.cAllocfLAI.funHandle(f,fe,fx,s,d,p,info,tix);        % effect of LAI on carbon allocation 
    [f,fe,fx,s,d,p]     =   ms.cAllocfwSoil.funHandle(f,fe,fx,s,d,p,info,tix);      % effect of soil moisture on carbon allocation 
    [f,fe,fx,s,d,p]     =   ms.cAllocfTsoil.funHandle(f,fe,fx,s,d,p,info,tix);      % effect of soil temperature on carbon allocation 
    [f,fe,fx,s,d,p]     =   ms.cAllocfNut.funHandle(f,fe,fx,s,d,p,info,tix);        % (pseudo)effect of nutrients on carbon allocation 
    [f,fe,fx,s,d,p]     =   ms.cAlloc.funHandle(f,fe,fx,s,d,p,info,tix);            % combine the different effects of carbon allocation 
    [f,fe,fx,s,d,p]     =   ms.cAllocfTreeCover.funHandle(f,fe,fx,s,d,p,info,tix);  % adjustment of carbon allocation according to tree cover
    % ---------------------------------------------------------------------
    % 6 - Autotrophic respiration
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =    ms.RAact.funHandle(f,fe,fx,s,d,p,info,tix);            % determine growth and maintenance respiration -> NPP
    % ---------------------------------------------------------------------
    % 7 - Carbon transfers to soil pools
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.cFlowfpSoil.funHandle(f,fe,fx,s,d,p,info,tix);       % effect of soil properties on the C transfers between pools
    [f,fe,fx,s,d,p]     =   ms.cFlowfpVeg.funHandle(f,fe,fx,s,d,p,info,tix);        % effect of vegetation properties on the C transfers between pools
    [f,fe,fx,s,d,p]     =   ms.cFlowAct.funHandle(f,fe,fx,s,d,p,info,tix);          % actual transfers of C between pools (of diagonal components)
    [f,fe,fx,s,d,p]     =   ms.cCycle.funHandle(f,fe,fx,s,d,p,info,tix);            % allocate carbon to vegetation components
                                                                                    % litterfall and litter scalars
                                                                                    % calculate carbon cycle/decomposition/respiration in soil
    [f,fe,fx,s,d,p]     =   ms.wSoilUpflow.funHandle(f,fe,fx,s,d,p,info,tix);       % Flux of water from lower to upper soil layers (upward soil moisture movement)
    [f,fe,fx,s,d,p]     =   ms.wGW2wSurf.funHandle(f,fe,fx,s,d,p,info,tix);         % water exchange between surface and groundwater
    % ---------------------------------------------------------------------
    % sum up components of fluxes and states, river routing, and water balance
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]     =   ms.sumVariables.funHandle(f,fe,fx,s,d,p,info,tix);      % sum variables (through modelRun.json)
    [f,fe,fx,s,d,p]     =   ms.riverRouting.funHandle(f,fe,fx,s,d,p,info,tix);      % sum variables (through modelRun.json)
    [f,fe,fx,s,d,p]     =   ms.wBalance.funHandle(f,fe,fx,s,d,p,info,tix);          % calculate the water balance    
    % ---------------------------------------------------------------------
    % Gather all variables that are desired and insert them
    % in fx,s,d
    % ---------------------------------------------------------------------
    [f,fe,fx,s,d,p]	    =   ms.storeStates.funHandle(f,fe,fx,s,d,p,info,tix);       % store current states in previous state variables 
end 
end
