% a script to run an experiment to optimize one fluxnet site
try
    gone
catch
end

%% setup paths
for fn = {'tools','model','optimization'}
    addpath(genpath(['../../' fn{1}]),'-begin')
end
outpath='/Net/Groups/BGI/work_3/sindbad/data/testBeds/output';
inpath='/Net/Groups/BGI/work_3/sindbad/data/testBeds/input/US-Ha1.2000-2015.nc';

%% provide an experiment configuration file
expConfigFile               =   'testBeds/optimize_fluxnet_site/settings_optimize_fluxnet_site/experiment_runOpti.json';

 % setup explicit spinup
%strN        = '% setup explicit spinup';
%strN2       = 'explicit';
zSequence   = struct(...
'funHandleSpin',{'runCoreTEM','runCoreTEM','spin_cCycle_CASA','runCoreTEM'},...
'funHandleStop',{[],[],[],[]},...
'funAddInputs',{{1,0,0},{0,1,0},{21},{0,1,0}},...
'nLoops',{1,20,1,1}...
); 

%% run the experiment
[f,fe,fx,s,d,p,precOnceData,info,fSU,feSU,fxSU,sSU,dSU,precOnceDataSU,infoSU,obs,cost] = workflowExperiment(expConfigFile, 'info.tem.spinup.sequence',zSequence,...
'info.tem.spinup.flags.recycleMSC', true,...
'info.tem.spinup.flags.saveSpinup', false,...
'info.tem.forcing.oneDataPath',inpath,...
'info.experiment.outputDirPath',outpath,...
'info.opti.constraints.oneDataPath',inpath...
);
