site_name: SINDBAD
pages:
    - About SINDBAD: index.md
    - Accessing SINDBAD : access.md
    - Concept & Definitions: concept.md
    - SINDBAD info: info.md
    - SINDBAD Structures: structures.md
    - Coding Conventions: conventions.md
    - Configuration Files: configuration.md
    - SINDBAD Optimization: optimization.md 
theme: readthedocs
