function [fe,fx,d,p,f] = cTauAct_simple(f,fe,fx,s,d,p,info,tix)
% combine all the effects that change the turnover rates (k)
p.cTauAct.k = ...
            p.cTauAct.k .* ...
            p.cTaufLAI.kfLAI .* ...
            p.cTaufpSoil.kfSoil .* ...
            p.cTaufpVeg.kfVeg .* ...
            fe.cTaufTsoil.fT(:,tix) .* ...
            d.cTaufwSoil.fwSoil(:,tix);
% note, we are multiplying [nPix,nZix]x[nPix,1] should be OK!
end %function
