function [fe,fx,d,p,f] = cTauAct_simple(f,fe,fx,s,d,p,info,tix)
% combine all the effects that change the turnover rates (k)

s.cd.p_cTauAct_k = ...
            s.cd.p_cCycleBase_k .* ...
            s.cd.p_cTaufLAI_kfLAI .* ...
            s.cd.p_cTaufpSoil_kfSoil .* ...
            s.cd.p_cTaufpVeg_kfVeg .* ...
            fe.cTaufTsoil.fT(:,tix) .* ...
            d.cTaufwSoil.fwSoil(:,tix);
% note, we are multiplying [nPix,nZix]x[nPix,1] should be OK!
end %function
